### ISSUE TITLE
About the length of generated waveform

### ISSUE THREAD

**Issue by ikou-austin** [NXTProduct/TUNet#2]
I found that the waveform generated using this model has a tiny variation on its length in the time direction, is this normal? Is there a way to eliminate this variation in time length to achieve accurate alignment?

**Comment by anhnv125** [comment]
Yes, you're right. I do some trimming in the dataloader to make to audio length divisible to hop_size. Instead of trimming, you can pad the audio with zeros then trim the padding after inferencing.
